### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by 6en6ar** [progscrape/urlnorm#1]
Maintainer note:

This issue was removed and user was blocked, as they reported a fake CVE after filing this issue.

**Comment by 6en6ar** [comment]
Hey team,

Since there is no response I will post the issue here in case You are interested to hear about it more.

The regex defined on line 37. in https://github.com/progscrape/urlnorm/blob/main/src/lib.rs used for trimming .html and other extensions when normalizing the url is vulnerable to a Regex Denial of Service when malicious input is provided.
In this example a string ".htmlA5.htmlA5.htmlA5" placed in the pathname of the url and repeated 50 000 times can cause delay.
The payload used:
**_let x = std::iter::repeat("A5.html").take(50000).collect::<String>().to_owned();_**

**Comment by mmastrac** [comment]
Thanks - I'll take a look at fixing this.

**Comment by mmastrac** [comment]
I'm unable to reproduce this. Can you provide a more detailed reproduction?

```

    #[rstest]
    fn test_denial_of_service(norm: UrlNormalizer) {
        let x = std::iter::repeat("a5.html").take(50000).collect::<Vec<_>>().join("");
        let url = Url::parse(&format!("http://google.com/{x}")).unwrap();
        norm.compute_normalization_string(&url);
    }

```

**Comment by 6en6ar** [comment]
Hey thanks for responding.
Try this.

```
use url::Url;
use urlnorm::UrlNormalizer;
use std::{time::{Duration, Instant}};

fn main() {
    println!("[ + ] Testing urlnorm package");
    let x = std::iter::repeat("A5.html").take(50000).collect::<String>().to_owned();
    let norm = UrlNormalizer::default();

    let mut url_input ="https://goooooooogle.com/hello/index.html/".to_owned();
    url_input.push_str(x.as_str());
    url_input.push_str("\x00");

    let url = Url::parse(&url_input).unwrap();
    println!("{:?}",url);
    let start = Instant::now();
    let normalized = norm.compute_normalization_string(&url);
    //let normalized = norm.normalize_host(&url).unwrap();
    println!("[ + ] Url -> {:?}", normalized);
    let end = start.elapsed();
    println!("[ + ] Time elapsed {:?}", end);
}
```

**Comment by mmastrac** [comment]
I see `[ + ] Time elapsed 77.053167ms` which is pretty reasonable for the size of this URL. It's expensive, but not entirely unreasonable considering the size of the URL. 

I can add a note to the package that users may wish to limit the size of URLs that they parse.

**Comment by mmastrac** [comment]
Actually, it's not even that bad - I disabled printing for the long URLs:

```
running 1 test
[ + ] Testing urlnorm package
[ + ] Time elapsed 155.084µs
test test::test_dos2 ... ok
```

**Comment by mmastrac** [comment]
Closing for now, but please let me know if you can reproduce.
